# compose.yaml
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hellokitty_user
      POSTGRES_PASSWORD: hellokitty_password
      POSTGRES_DB: hellokitty_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ✨ Added Redis for Caching and Message Queues!
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  # 3. MongoDB for Chat/Unstructured Data
  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: hellokitty_mongo
      MONGO_INITDB_ROOT_PASSWORD: hellokitty_mongo_pass
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # 4. RabbitMQ for Microservice Events
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672' # The connection port
      - '15672:15672' # The Web UI dashboard
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    # 5. KONG API GATEWAY
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: 'off' # DB-less mode
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - '8000:8000' # Your Frontend will now talk to port 8000!
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  rabbitmq_data:
  kong_data:
