services:
  # 1. THE AUTHENTICATION API
  - type: web
    name: hellokitty-auth-api
    runtime: node
    region: ohio
    plan: free
    # Generate the IAM Postgres Client, then build auth-api
    buildCommand: 'pnpm install --frozen-lockfile && npx prisma generate --schema=libs/iam/data-access/prisma/schema.prisma && pnpm nx build auth-api'
    startCommand: node dist/apps/auth-api/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_DATABASE_URL
        sync: false

  # 2. THE SOCIAL MEDIA API
  - type: web
    name: hellokitty-social-api
    runtime: node
    region: ohio
    plan: free
    # Generate the Social Mongo Client, then build social-api
    buildCommand: 'pnpm install --frozen-lockfile && npx prisma generate --schema=libs/social/data-access/prisma/schema.prisma && pnpm nx build social-api'
    startCommand: node dist/apps/social-api/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOCIAL_DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
